### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by K-zhy** [Yan0613/MIT6.824#1]
博主您好
lab1中，在运行 `go run mrworker.go wc.so` 生成的文件名是mr-数字-数字，reruce阶段没有生成mr-out-*文件

**Comment by Yan0613** [comment]
> 博主您好 lab1中，在运行 `go run mrworker.go wc.so` 生成的文件名是mr-数字-数字，reruce阶段没有生成mr-out-*文件

请问有具体情况吗？或者截个图，我这边可以成功运行通过测试

**Comment by K-zhy** [comment]
请问你的运行环境是什么？ 推测了一下原因：test-mr.sh对程序的运行时间有限制，我的环境是win上的Linux虚拟机，跑第一个测试的时候比较慢，reduce没有执行便被提前终止了。导致mr-out-*还没有来得及生成，可能是这个原因。

**Comment by Yan0613** [comment]
> 请问你的运行环境是什么？ 推测了一下原因：test-mr.sh对程序的运行时间有限制，我的环境是win上的Linux虚拟机，跑第一个测试的时候比较慢，reduce没有执行便被提前终止了。导致mr-out-*还没有来得及生成，可能是这个原因。

我这个项目是win的环境，或许你多启动几次，改一下.sh文件试试呢？

**Comment by K-zhy** [comment]
> > 请问你的运行环境是什么？ 推测了一下原因：test-mr.sh对程序的运行时间有限制，我的环境是win上的Linux虚拟机，跑第一个测试的时候比较慢，reduce没有执行便被提前终止了。导致mr-out-*还没有来得及生成，可能是这个原因。
> 
> 我这个项目是win的环境，或许你多启动几次，改一下.sh文件试试呢？

感谢，调大程序限制时间可以跑通test。请问你是直接在win中运行没有用虚拟机吗？ 搞不太懂我这个在虚拟机上跑为何这么慢。

**Comment by Yan0613** [comment]
> > > 请问你的运行环境是什么？ 推测了一下原因：test-mr.sh对程序的运行时间有限制，我的环境是win上的Linux虚拟机，跑第一个测试的时候比较慢，reduce没有执行便被提前终止了。导致mr-out-*还没有来得及生成，可能是这个原因。
> > 
> > 
> > 我这个项目是win的环境，或许你多启动几次，改一下.sh文件试试呢？
> 
> 感谢，调大程序限制时间可以跑通test。请问你是直接在win中运行没有用虚拟机吗？ 搞不太懂我这个在虚拟机上跑为何这么慢。

我没有用虚拟机，我之前也有用过WSL，但是后来感觉还是不方便，坑略多，就换回来了

**Comment by K-zhy** [comment]
> > > > 请问你的运行环境是什么？ 推测了一下原因：test-mr.sh对程序的运行时间有限制，我的环境是win上的Linux虚拟机，跑第一个测试的时候比较慢，reduce没有执行便被提前终止了。导致mr-out-*还没有来得及生成，可能是这个原因。
> > > 
> > > 
> > > 我这个项目是win的环境，或许你多启动几次，改一下.sh文件试试呢？
> > 
> > 
> > 感谢，调大程序限制时间可以跑通test。请问你是直接在win中运行没有用虚拟机吗？ 搞不太懂我这个在虚拟机上跑为何这么慢。
> 
> 我没有用虚拟机，我之前也有用过WSL，但是后来感觉还是不方便，坑略多，就换回来了

感谢🙇‍ 那应在虚拟机上跑的慢应该就是问题所在了。
